FROM node:14.15.3

ARG EMAIL_SERVER_ENDPOINT=${EMAIL_SERVER_ENDPOINT}
ARG EMAIL_SERVER_PASSWORD=${EMAIL_PASSWORD}
ARG MONGO_DB=${MONGO_DB}
ARG JWT_SECRET=${JWT_SECRET}
ARG GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
ARG GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
ARG GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
ARG GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
ARG LASTFM_KEY=${LASTFM_KEY}
ARG LASTFM_SECRET=${LASTFM_SECRET}
RUN mkdir -p /usr/src/nuxt-app
WORKDIR /usr/src/nuxt-app
COPY . /usr/src/nuxt-app/

RUN npm install
RUN npm run build

EXPOSE 80

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=80

CMD [ "npm", "run", "start" ]
